server:
  servlet:
    context-path: /power-ledger

spring:
  application:
    name: pl-code-challenge
  datasource:
    url: ${DB_URL:jdbc:h2:mem:pldb}
    username: ${DB_USER:root}
    password: ${DB_PASS:root123}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    producer:
      bootstrap-servers: ${KAFA_SERVER:172.16.134.40:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${KAFA_SERVER:172.16.134.40:9092}
      group-id: battery
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:172.16.134.40}
    port: ${REDIS_PORT:6379}

app:
  jwt:
    secret: ${JWT_SECRET:plc}
