spring:
  application:
    name: pl-code-challenge
  datasource:
    url: jdbc:h2:mem:pldb
    username: root
    password: root123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
